language: go
go: 1.7
sudo: false

script: make release

deploy:
  provider: releases
  edge:
    source: jawher/dpl
    branch: named-releases-files
  api_key:
    secure: "XW7ZMGmDT6PFIYSHj1Q3dSoCrPRPxlaitO/9VMWKyK6G6cpauAk6+5wIKrRZCbcFYjE+63vtjUDxSn5q2IEIz4mKfGyr6qxEctFg3kTAkQWLxsPaRn55hq0431uGwg4w//F5Kg50YaI7+CC7nxqAJ3Kf6/+L/7/usfyXtJUUFOAA+caEVSWJPbAL1MhHz8JBbw3oDlKefojuty+9MPWGQ2wxzq7PK4n2UDpRAGW5stFBkHaF+e2wwC2cX+jpARcHwCE1ziLjmE+DHzXt5pm9CuM+xDAgWSz8NwqsXdFS9pSuWUTTktAE6s9L7NNDvnv74dBdX6+Kg7L4vKkQK/xIlL+jndMLth6iil9hE7pYoXpGf/u9ZOHHob2OOfymAUOS4VEUYurbhyql3YKhSV7T50l13P5VGiB/dYi/0Mkw6Ikx5cfgI86B4KGlpZ4Wv0U0KTY5LAPAUHwmPV1uJF3BfTRBsnLbn4VoLwznBMOLNQrZgoo9IxF25K936Ts6ReBOtDFC28wkm6oxszMAjIcDnz6Xk8eLDL64dI26Xoswi/2U14e1eXKV3xtGemXk4+Znry7+omWRFpyPTiRJf4vZ1X8/cVGnCsEXiYalzXYzaVGd+QfOAO4Ojd3UVLvF8n0vuXkW2ZeBs2pae5g9Wgx/MnJISu3youpy/ehtLcEufOE="
  file:
  - path: bin/linux/test
    name: test (Linux)
  - path: bin/darwin/test
    name: test (Mac OS)
  skip_cleanup: true
  on:
    all_branches: true
